### ISSUE TITLE
The tutorial Python is full of errors

### ISSUE THREAD

**Issue by AJenbo** [zerotier/libzt#204]
https://docs.zerotier.com/sockets/tutorial.html

Looks like some examples are using two different versions of the extension:
![image](https://user-images.githubusercontent.com/204594/211129409-00b1a096-b247-4885-94c8-38a3a071bf0e.png)

Also some times the node is named `n` and others it's called `node`, sometimes in the same snippet:
![image](https://user-images.githubusercontent.com/204594/211129427-17f9d208-18d5-480a-8c23-e6a183155a46.png)

Sometimes print is even used incorrectly:
![image](https://user-images.githubusercontent.com/204594/211129438-027e5c8e-6d28-4d0f-a93c-e0ad6fe3b86a.png)
`TypeError: can only concatenate str (not "int") to str`

This makes getting up and running a bit of a pain :(

**Comment by joseph-henry** [comment]
Sorry about that. Typos have been fixed in this commit https://github.com/zerotier/docs/commit/f89d7495b378d46a8049bda684fbac1bc55cbb65

Looks like at some point the python package broke again. I'll be issuing an update again soon.

**Comment by AJenbo** [comment]
Thanks, you missed one discrepancy (issue was not the most organized, sorry for that):

```python
node.start();
```
vs

```python
node.node_start()
```

It's something that changed between versions of the extension
